"""Reproducible ablation of the wall/footprint stage on the FURNISHED SYNTHETIC room (tests/synth_cloud.py).
SYNTHETIC ONLY: it shows that each mechanism does what it claims on a scene built to contain the failure modes seen in the first real
scan. It says nothing about real-data accuracy. Usage:  python scripts/synthetic_wall_ablation.py [--out docs/synthetic_wall_ablation.md]"""
from __future__ import annotations

import argparse
import copy
import itertools
import logging
import sys
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parents[1]
sys.path[:0] = [str(ROOT / "src"), str(ROOT / "tests")]
from applied_ai.config import load_config  # noqa: E402
from applied_ai.geometry.floorplan import floor_footprint  # noqa: E402
from applied_ai.geometry.room_layout import extract_walls  # noqa: E402
from applied_ai.geometry.walls import wall_length  # noqa: E402
from synth_cloud import furnished_room  # noqa: E402


def variants(base):
    def mk(method, ext, closing, crossing=False):
        c = copy.deepcopy(base)
        c["walls"]["method"], c["walls"]["min_column_extent_m"] = method, ext
        c["walls"]["corner_extend_m"] = 1.0 if closing else 0.0
        c["walls"]["manhattan"]["drop_non_conforming"] = closing
        c["floorplan"]["prefer_wall_enclosed"] = closing
        c["walls"]["camera_crossing"]["enabled"] = crossing
        return c
    return {
        "A. before: legacy RANSAC, no filter, evidence area": mk("legacy_ransac", 0.0, False),
        "B. legacy RANSAC + column filter": mk("legacy_ransac", 0.4, False),
        "C. axis walls + closing, NO column filter": mk("manhattan_axes", 0.0, True),
        "D. axis walls + closing + column filter (new default)": mk("manhattan_axes", 0.4, True, crossing=True),
    }


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default=None)
    a = ap.parse_args()
    logging.disable(logging.WARNING)
    base = load_config()
    rows = []
    for name, cfg in variants(base).items():
        err, werr, nw, off_axis = [], [], [], 0
        for seed, rot in itertools.product(range(3), (5.0, 18.0, 37.0, 63.0)):
            L, cam, gt = furnished_room(seed=seed, rot_deg=rot)
            wl = extract_walls(L, cam, 2.6, cfg)
            fp = floor_footprint(L, wl["final"], cfg, cam)
            err.append(100 * (fp["area_m2"] / gt["area"] - 1))
            lens = [wall_length(w) for w in wl["final"]]
            werr.append(max(min(abs(x - g) for x in lens) for g in gt["wall_lengths"]))
            nw.append(len(wl["final"]))
            off_axis += sum(1 for w in wl["final"] if not w.get("regularized"))
        err = np.array(err)
        rows.append((name, np.median(err), np.abs(err).max(), np.median(nw), max(nw), max(werr), off_axis))
    lines = ["| variant | median area err % | worst abs area err % | median walls | max walls | worst true-wall length err (m) | un-regularized walls kept |",
             "|---|---|---|---|---|---|---|"]
    lines += [f"| {n} | {m:+.1f} | {w:.1f} | {int(mn)} | {mx} | {we:.2f} | {oa} |" for n, m, w, mn, mx, we, oa in rows]
    txt = "\n".join(lines)
    print(txt)
    if a.out:
        Path(a.out).write_text("# Synthetic wall/footprint ablation (GENERATED - synthetic furnished room only)\n\n"
                               "Generated by `python scripts/synthetic_wall_ablation.py`. 12 scenes = 3 seeds x 4 room rotations (5/18/37/63 deg). Ground truth: a 5.9 x 3.7 m "
                               "room (21.83 m2) containing a wardrobe hiding 1.8 m of wall, a table, a low bed, an off-axis screen, patchy floor evidence and a corridor seen through "
                               "a door. **This validates pipeline logic only; it is not evidence of accuracy on real scans.**\n\n" + txt + "\n")


if __name__ == "__main__":
    main()
